[project]
name = "knowledge-graph-and-rag"
version = "0.1.0"
description = "Knowledge Graph construction used to make RAG applications."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
